Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,9 +12,19 @@ jobs:
     runs-on: 'ubuntu-latest'
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Deploy
-      run: echo ${{ github.event.inputs.version }}
+      - name: Verify tag exists
+        run: |
+            TAG_EXISTS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              "https://api.github.com/repos/${{ github.repository }}/git/ref/tags/${{ github.event.inputs.version }}" | jq -r ".ref")
+            
+            if [ "$TAG_EXISTS" == "null" ]; then
+              echo "Error: Tag ${{ github.event.inputs.version }} does not exist!"
+              exit 1
+            fi
+          
+      - name: Checkout code
+        uses: actions/checkout@v2
+      
+      - name: Deploy
+        run: echo ${{ github.event.inputs.version }}
 
